package ec.edu.espe.registersystemmaven.view;

/**
 *
 * @author Logic Legion, DCCO-ESPE
 */
public class FrmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdmin
     */
    public FrmAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUser = new javax.swing.JMenu();
        mnuiProfile = new javax.swing.JMenuItem();
        mnuiLogout = new javax.swing.JMenuItem();
        mnuiExit = new javax.swing.JMenuItem();
        mnuStudent = new javax.swing.JMenu();
        mnuiCourse = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuTutor = new javax.swing.JMenu();
        mnuiAddTutors = new javax.swing.JMenuItem();
        mnuiManageAccounts = new javax.swing.JMenuItem();
        mnuiManageTutors = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        mnuiComputeGrades = new javax.swing.JMenuItem();
        mnuiComputeGratuity = new javax.swing.JMenuItem();
        mnuiViewReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        mnuUser.setText("Administrador");

        mnuiProfile.setText("Perfil");
        mnuiProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiProfileActionPerformed(evt);
            }
        });
        mnuUser.add(mnuiProfile);

        mnuiLogout.setText("Cerrar Sesión");
        mnuiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiLogoutActionPerformed(evt);
            }
        });
        mnuUser.add(mnuiLogout);

        mnuiExit.setText("Salir");
        mnuiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiExitActionPerformed(evt);
            }
        });
        mnuUser.add(mnuiExit);

        jMenuBar1.add(mnuUser);

        mnuStudent.setText("Estudiante");

        mnuiCourse.setText("Agregar Estudiante al Curso");
        mnuiCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCourseActionPerformed(evt);
            }
        });
        mnuStudent.add(mnuiCourse);

        jMenu1.setText("Buscar Estudiante");

        jMenuItem1.setText("Por Cedula");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Por Nombre");
        jMenu1.add(jMenuItem2);

        mnuStudent.add(jMenu1);

        jMenuItem3.setText("Eliminar Estudiante");
        mnuStudent.add(jMenuItem3);

        jMenuItem4.setText("Editar información del estudiante");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuStudent.add(jMenuItem4);

        jMenuBar1.add(mnuStudent);

        mnuTutor.setText("Profesores");

        mnuiAddTutors.setText("Agregar Profesores");
        mnuiAddTutors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiAddTutorsActionPerformed(evt);
            }
        });
        mnuTutor.add(mnuiAddTutors);

        mnuiManageAccounts.setText("Administrar Cuentas");
        mnuTutor.add(mnuiManageAccounts);

        mnuiManageTutors.setText("Administrar Profesores");
        mnuTutor.add(mnuiManageTutors);

        jMenuBar1.add(mnuTutor);

        mnuReport.setText("Reporte");

        mnuiComputeGrades.setText("Calcular notas");
        mnuReport.add(mnuiComputeGrades);

        mnuiComputeGratuity.setText("Calcular Gratuidad");
        mnuReport.add(mnuiComputeGratuity);

        mnuiViewReport.setText("Ver Reporte General");
        mnuReport.add(mnuiViewReport);

        jMenuBar1.add(mnuReport);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuiProfileActionPerformed

    private void mnuiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiExitActionPerformed
        System.exit(0);        
    }//GEN-LAST:event_mnuiExitActionPerformed

    private void mnuiCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCourseActionPerformed
        FrmAddStudent frmaddstudent = new FrmAddStudent();
        this.setVisible(false);
        frmaddstudent.setVisible(true);
    }//GEN-LAST:event_mnuiCourseActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnuiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiLogoutActionPerformed
        FrmLogin frmlogin = new FrmLogin();
        this.setVisible(false);
        frmlogin.setVisible(true);
    }//GEN-LAST:event_mnuiLogoutActionPerformed

    private void mnuiAddTutorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiAddTutorsActionPerformed
        FrmAddTutor frmtutor = new FrmAddTutor();
        this. setVisible(false);
        frmtutor.setVisible(true);
    }//GEN-LAST:event_mnuiAddTutorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuReport;
    private javax.swing.JMenu mnuStudent;
    private javax.swing.JMenu mnuTutor;
    private javax.swing.JMenu mnuUser;
    private javax.swing.JMenuItem mnuiAddTutors;
    private javax.swing.JMenuItem mnuiComputeGrades;
    private javax.swing.JMenuItem mnuiComputeGratuity;
    private javax.swing.JMenuItem mnuiCourse;
    private javax.swing.JMenuItem mnuiExit;
    private javax.swing.JMenuItem mnuiLogout;
    private javax.swing.JMenuItem mnuiManageAccounts;
    private javax.swing.JMenuItem mnuiManageTutors;
    private javax.swing.JMenuItem mnuiProfile;
    private javax.swing.JMenuItem mnuiViewReport;
    // End of variables declaration//GEN-END:variables
}
